import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '🚀 Start Here',
      items: [
        'getting-started/role-understanding',
        'getting-started/skill-gap-template',
        'roadmap/roadmap-16-weeks',
        'roadmap/schedules-and-metrics',
      ],
    },
    {
      type: 'category',
      label: '🏗️ Foundations & DSA',
      items: [
        'topic-banks/dsa-backend-plan',
        {
          type: 'category',
          label: 'Hand-Picked Problems',
          items: [
            'dsa-problems/two-sum',
            'dsa-problems/lru-cache',
            'dsa-problems/merge-intervals',
          ],
        },
        'topic-banks/theory-round',
      ],
    },
    {
      type: 'category',
      label: '🏛️ System Design & Architecture',
      items: [
        'topic-banks/machine-coding-bank',
        'topic-banks/system-design',
        'topic-banks/advanced-backend',
      ],
    },
    {
      type: 'category',
      label: '🛠️ Execution & Strategy',
      items: [
        'topic-banks/projects',
        'interview/interview-prep-playbook',
        'resources/resources',
        'resources/go-resources',
      ],
    },
    {
      type: 'category',
      label: '📅 Weekly Schedule',
      items: [
        {
          type: 'autogenerated',
          dirName: 'weeks',
        },
      ],
    },
  ],
};

export default sidebars;
